name: bank_lakehouse
version: "1.0.0"
config-version: 2
profile: lakehouse
model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ["tests"]
snapshot-paths: ["snapshots"]
target-path: target
clean-targets: ["target", "dbt_packages"]
models:
  bank_lakehouse:
    bronze:
      +schema: bronze
    silver:
      +schema: silver
    gold:
      +schema: gold
